# Generated by Django 4.2.7 on 2024-12-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0003_alter_participant_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
